# Docker Compose file for the microservices using PostgreSQL database in Render
version: '3.8'

services:
  book_catalog:
    build:
      context: .
      dockerfile: ./book_catalog/Dockerfile
    environment:
      DATABASE_URL: postgresql://miranda_pena_carrasquillo:5K0QsSQvdlIUFeizNDewOvul7jdPGs6z@dpg-crfskcbv2p9s73a2b9lg-a.singapore-postgres.render.com/library_db_izwe
    ports:
      - "8000:8000"
    networks:
      - microservices_network

  inventory_management:
    build:
      context: .
      dockerfile: ./inventory_management/Dockerfile
    environment:
      DATABASE_URL: postgresql://miranda_pena_carrasquillo:5K0QsSQvdlIUFeizNDewOvul7jdPGs6z@dpg-crfskcbv2p9s73a2b9lg-a.singapore-postgres.render.com/library_db_izwe
    ports:
      - "8001:8000"
    networks:
      - microservices_network

networks:
  microservices_network: